### ISSUE TITLE
[Feature Request] How can I modify the speeds presets ?

### ISSUE THREAD

**Issue by lorenuars19** [dsp-mods/DSP-game-speed#7]
**Is your feature request related to a problem? Please describe.**
Not, really a problem, I would love just having a config file, where you can tweak the speed values

**Comment by yohanneshabte** [comment]
I can easily add a config file to add more speed options. I have hard-coded the 2x, and 3x speed and didn't want to add more because when I tested the performance at higher speeds(20-30x and more) it is very hard to control your player. But it may be feasible to use when in warp mode to a distant systems, or just speeding up your sphere builds etc...
I will add a "Left Alt + 0" shortcut to toggle the speed preset in your config file. Just be careful if you want to set large numbers on the multiplier. Since the mod works by increasing the time scale of the engine, I don't know how far you can push it and how it affects your framerate and performance. Give me a day or two to add it in. Thanks for the suggestion!

**Comment by lorenuars19** [comment]
Thanks.

**Comment by yohanneshabte** [comment]
I have finished modifying the mod to use config files. I'll add the update on the mod manger as well. Thanks for your patience. I  had a busy week. Just got enough time to work on it.
